name: GitHub Pages Deploy

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write

jobs:
  build:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}

      - name: Install and build
        run: npm install && npm run build && cp docs/index.html docs/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
